# Generated by Django 4.2.11 on 2024-03-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_data", models.CharField(max_length=1000)),
                ("service_id", models.CharField(max_length=100)),
                ("event_time", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=100)),
                (
                    "image_Value",
                    models.CharField(blank=True, max_length=10240, null=True),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=100)),
            ],
        ),
    ]
