# Generated by Django 4.2.11 on 2024-03-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EggData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_data", models.CharField(max_length=1000)),
                ("service_id", models.CharField(max_length=100)),
                ("event_time", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=100)),
                (
                    "egg_Value",
                    models.CharField(blank=True, max_length=10240, null=True),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FoodData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_data", models.CharField(max_length=1000)),
                ("service_id", models.CharField(max_length=100)),
                ("event_time", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=100)),
                ("class_name", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FruitData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_data", models.CharField(max_length=1000)),
                ("service_id", models.CharField(max_length=100)),
                ("event_time", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=100)),
                (
                    "fruit_Value",
                    models.CharField(blank=True, max_length=10240, null=True),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SmokeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_data", models.CharField(max_length=1000)),
                ("service_id", models.CharField(max_length=100)),
                ("event_time", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=100)),
                (
                    "smoke_Value",
                    models.CharField(blank=True, max_length=10240, null=True),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ToyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_data", models.CharField(max_length=1000)),
                ("service_id", models.CharField(max_length=100)),
                ("event_time", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=100)),
                (
                    "toy_Value",
                    models.CharField(blank=True, max_length=10240, null=True),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=100)),
            ],
        ),
    ]
