# Generated by Django 4.2.11 on 2024-03-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_eggdata_fooddata_fruitdata_smokedata_toydata"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatteryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_data", models.CharField(max_length=1000)),
                ("service_id", models.CharField(max_length=100)),
                ("event_time", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=100)),
                (
                    "battery_Value",
                    models.CharField(blank=True, max_length=10240, null=True),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BoxData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_data", models.CharField(max_length=1000)),
                ("service_id", models.CharField(max_length=100)),
                ("event_time", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=100)),
                (
                    "box_Value",
                    models.CharField(blank=True, max_length=10240, null=True),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MedicineData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_data", models.CharField(max_length=1000)),
                ("service_id", models.CharField(max_length=100)),
                ("event_time", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=100)),
                (
                    "medicine_Value",
                    models.CharField(blank=True, max_length=10240, null=True),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("score", models.CharField(max_length=100)),
            ],
        ),
    ]
